In [1]:
import simpy
import pandas as pd
import numpy as np 
#from collections import namedtuple
#from recordtype import recordtype
import random 
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
from prettytable import PrettyTable
#get_ipython().magic('matplotlib inline')
#from keras.models import Sequential
#from keras.layers import Dense, Dropout
#from keras.optimizers import Adam 
from collections import deque 
from itertools import product
import math
from DQN import DQN
        
def episode(env,DQN,Tsc,Tfu,allowed_actions): #pacing rate가 각 flow에게 할당
    global action
    global state
    global request
    global flow_success
    fs=request['filesize']
    cnt=1
    c=0
    dqn_agent = DQN()
    while True: #Simularion time 동안 episode를 반복한다
        print ("-------------")
        print("Episode start",cnt)
        print ("")
        first_action=1 #new action의 경우 학습데이터에 추가하지 않음
        
        #1개의 에피소드는 모든 filesize가 0이 될때까지 실행
        while ((request['filesize'][0]!=0)or(request['filesize'][1]!=0)or(request['filesize'][2]!=0)):#모두 전송이 완료될 때 까지
            c+=1
            try: #state = filesize/deadline
                state=[math.ceil(request['filesize'][s]/request['deadline'][s]) for s in range(len(request['sources']))]
            except:#deadline이 0인 source가 존재하는 경우 (0 division 에러)
                for s in range(len(sources)):#deadline이 0이 아닌 source는 그대로
                    if (request['deadline'][s] != 0):
                        state[s]= math.ceil(request['filesize'][s]/request['deadline'][s])
                    else:#deadline이 0인 source의 state는 0
                        state[s]=0

            if (first_action==1): #New state-action policy를 EDF방식으로 (가장 deadline이 시급한)     
                action=[0,0,0]
                index=np.argmin(request['deadline']) #deadline 최소인 source의 index
                action[index]=10 #bottleneck capacity
                
            else: 
                action,p=dqn_agent.choose_action(state,allowed_actions) #DQN에 의한 액션선택
                pexp.append(p)
                

            for i in range(Tsc):#Scheduling interval 시작
                for s in range(len(sources)): #각 source에 대해 반복
                    request['filesize'][s]=max([request['filesize'][s]-int(action[s]*1024/10),0]) #음수 X
                    request['deadline'][s]=max(request['deadline'][s]-1,0) #음수 X, deadline은 Tsc만큼 감소
                    # deadline을 양수로 해야하는 이유 > 음수면  value가 1로 할당됨
                    if ((request['filesize'][s]==0) and (request['value'][s]==None)): #아직 완료되지 않았던 flow가 전송이 완료되면?
                        #print ("s{}의 전송이 완료됨".format(s))
                        if (request['deadline'][s]!=0): #기간 안에 전송되면?
                            request['value'][s]=1 #value를 1로 변경
                            flow_success.append(1)
                            print ("s{}의 전송이 deadline 안에 완료됨".format(s))
                        else: #기간안에 전송된게 아니라면(value초기값은 None)
                            request['value'][s]=0
                            flow_success.append(0)
                            print ("s{}의 전송이 deadline을 지나 완료됨".format(s))
                yield env.timeout(Tfu)# Tfu(1초)마다 위 과정 실행
            
            
            print ("action", action)
#             print ("")
#             print ("source 0 전송할 file:",request['filesize'][0])
#             print ("")
#             print ("source 1 전송할 file:",request['filesize'][1])
#             print ("")
#             print ("source 2 전송할 file:",request['filesize'][2])
        
            #모든 전송이 완료된 후 next_state는 고려할 필요 없음: terminal=True로 하여 target에 reward를 할당
            if ((request['filesize'][0]==0)and(request['filesize'][1]==0)and(request['filesize'][2]==0)):
                terminal = True
            else : 
                terminal = False
            
            
            try: 
                next_state=[math.ceil(request['filesize'][s]/request['deadline'][s]) for s in range(len(request['sources']))]
            except:#deadline이 0인 경우 error
                for s in range(len(sources)):
                    if (request['deadline'][s] != 0):
                        next_state[s]= math.ceil(request['filesize'][s]/request['deadline'][s])
                    else:
                        next_state[s]=0
                        
            #print(next_state)
                        
            # build your reward function 리워드 방정식 입력
            reward = sum((np.max(request['deadline'])-request['deadline'])*action)
            cur_state = state 
            action = action
            new_state = next_state 
            #new_action = next_allowed_actions
            reward = reward
            terminal = terminal
            
            if (first_action==0): # 첫번쨰 선택 액션이 아닌경우에만 학습
                dqn_agent.remember(cur_state, action, reward, new_state,terminal) #새로운 state로 설정해주고 기존state저장
                mse_loss.append(dqn_agent.replay(allowed_actions))#학습, loss 저장
                dqn_agent.train_target()
            
            first_action=0 

        for i in range(len(sources)):
            if (request['value'][i]==1):
                print ("source {} 전송완료".format(i))
            else:
                print ("source {} deadine 충족하지 못함".format(i))
        
        print("모두 전송 완료")

        filesize=[random.randrange(10,50)*1024 for source in range(len(sources))] #단위 Mb
        deadline=[int(filesize[source]/307) for source in range(len(sources))] #sum_rmin이  9
        request = {
            'sources' : sources,
            'destinations' : destinations, 
            'filesize' : filesize, #단위는 Gbps
            'deadline' : deadline,
            'value' : [None for source in sources] #아직 전송되지 않았으면 None, 제시간에 전송되었으면 1, 제시간에 전송되지 않았으면 0
        }#다음 episode를 위해 request 생성

        state=[0,0,0]#초기 state
        action=[0,0,0]#초기 action ->고칠것
        print ("episode end")
        print("-----------------")
        cnt+=1
    
    dqn_agent.save_model("policy_network.h5")
    
    


#한 번의 에피소드 프로세스
#N개의 source에서 동시에 request를 발생시키면 시작됨
#끝나는 기점은 모든 flow가 전송이 완료되는 시점
#랜덤으로 filesize를 생성, deadline도 랜덤으로 생성
env = simpy.Environment()

mse_loss=[] #episode의 진행에 따른 mse_loss의 변화율 graph
flow_success=[] #episode의 진행에 따른 flow_success rate
pexp=[] #action choice 진행에 따른 pexp 변화

state=[0,0,0]#초기 state
action=[0,0,0]#초기 action ->고칠것
Tsc=5 #scheduling interval을 구성하는 flow update interval의 수
Tfu=0.1 #flow update interval의 시간단위(0.1초로 가정)
sources = ['s0', 's1', 's2']
destinations = ['d0', 'd1', 'd2']
filesize=[random.randrange(10,50)*1024 for source in range(len(sources))] #단위 Mb
deadline=[int(filesize[source]/307) for source in range(len(sources))] #sum_rmin이  9
request = {
    'sources' : sources,
    'destinations' : destinations, 
    'filesize' : filesize, #단위는 Mbps
    'deadline' : deadline,
    'value' : [None for source in sources] #아직 전송되지 않았으면 None, 제시간에 전송되었으면 1, 제시간에 전송되지 않았으면 0
}

A=list(range(11))
B=list(range(11))
C=list(range(11)) 
allowed_actions=[] #합이 10이 되는 0~10까지의 수 조합
for i in list(product(*(A,B,C))):
    if sum(list(i))==10:
        allowed_actions.append(i) #d는 66개의 조합
        
#print ("action", action)
#print ("")
# print ("source 0 전송할 file:",request['filesize'][0])
# print ("")
# print ("source 1 전송할 file:",request['filesize'][1])
# print ("")
# print ("source 2 전송할 file:",request['filesize'][2])

# print ("source 0의 min_rate:",math.ceil(request['filesize'][0]/request['deadline'][0]))
# print("")
# print ("source 1의 min_rate:",math.ceil(request['filesize'][1]/request['deadline'][1]))
# print("")
# print ("source 0의 min_rate:",math.ceil(request['filesize'][2]/request['deadline'][2]))


env.process(episode(env,DQN,Tsc,Tfu,allowed_actions))
env.run(until=10000)#10만 초 동안 가동
print("종료")

#print (mse_loss)
#print (flow_success)


Using TensorFlow backend.
C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\user\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519

-------------
Episode start 1

action [0, 0, 10]
0.999
1
random action
action (9, 0, 1)
update weights
0.999
2
random action
action (4, 4, 2)
update weights
0.999
3
random action
action (0, 0, 10)
update weights
0.999
4
random action
action (6, 3, 1)
update weights
0.999
5
random action
action (5, 3, 2)
update weights
0.999
6
random action
action (1, 6, 3)
update weights
0.999
7
random action
action (2, 6, 2)
update weights
0.999
8
random action
action (5, 0, 5)
update weights
0.999
9
random action
action (2, 0, 8)
update weights
0.999
10
random action
action (6, 1, 3)
update weights
0.999
11
random action
action (5, 0, 5)
update weights
0.999
12
random action
action (2, 5, 3)
update weights
0.999
13
random action
action (4, 5, 1)
update weights
0.999
14
random action
action (6, 1, 3)
update weights
0.999
15
random action
action (5, 5, 0)
update weights
0.999
16
random action
action (6, 3, 1)
update weights
0.999
17
random action
action (6, 1, 3)
update weights
0.999
18
random action
a

update weights
0.999
131
random action
action (1, 0, 9)
update weights
0.999
132
random action
action (8, 1, 1)
update weights
0.999
133
random action
action (3, 2, 5)
update weights
0.999
134
random action
action (4, 3, 3)
update weights
0.999
135
random action
action (0, 7, 3)
update weights
0.999
136
random action
action (0, 8, 2)
update weights
0.999
137
random action
action (8, 0, 2)
update weights
0.999
138
random action
action (2, 2, 6)
update weights
0.999
139
random action
s2의 전송이 deadline 안에 완료됨
action (2, 2, 6)
update weights
0.999
140
random action
action (8, 0, 2)
update weights
0.999
141
random action
action (6, 4, 0)
update weights
0.999
142
random action
s1의 전송이 deadline을 지나 완료됨
action (0, 8, 2)
update weights
source 0 전송완료
source 1 deadine 충족하지 못함
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 6

action [0, 0, 10]
0.999
143
random action
action (0, 4, 6)
update weights
0.999
144
random action
action (3, 2, 5)
update weights
0.999
145
r

update weights
0.999
263
random action
action (6, 0, 4)
update weights
0.999
264
random action
action (10, 0, 0)
update weights
0.999
265
random action
action (3, 3, 4)
update weights
0.999
266
random action
s1의 전송이 deadline 안에 완료됨
action (3, 4, 3)
update weights
0.999
267
random action
action (0, 7, 3)
update weights
0.999
268
random action
action (7, 0, 3)
update weights
0.999
269
random action
action (4, 1, 5)
update weights
0.999
270
random action
action (6, 1, 3)
update weights
0.999
271
random action
action (0, 6, 4)
update weights
0.999
272
random action
s0의 전송이 deadline 안에 완료됨
action (9, 1, 0)
update weights
0.999
273
random action
action (3, 0, 7)
update weights
0.999
274
random action
action (2, 5, 3)
update weights
0.999
275
random action
action (6, 0, 4)
update weights
0.999
276
random action
action (3, 3, 4)
update weights
0.999
277
random action
s2의 전송이 deadline을 지나 완료됨
action (5, 1, 4)
update weights
source 0 전송완료
source 1 전송완료
source 2 deadine 충족하지 못함
모두 전송 완료
episode e

update weights
0.999
388
random action
action (6, 2, 2)
update weights
0.999
389
random action
action (1, 5, 4)
update weights
0.999
390
random action
s1의 전송이 deadline 안에 완료됨
action (4, 4, 2)
update weights
0.999
391
random action
action (3, 1, 6)
update weights
0.999
392
random action
action (8, 1, 1)
update weights
0.999
393
random action
action (3, 7, 0)
update weights
0.999
394
random action
action (4, 5, 1)
update weights
0.999
395
random action
action (3, 6, 1)
update weights
0.999
396
random action
action (2, 8, 0)
update weights
0.999
397
random action
action (0, 3, 7)
update weights
0.999
398
random action
s2의 전송이 deadline을 지나 완료됨
action (6, 2, 2)
update weights
0.999
399
random action
action (10, 0, 0)
update weights
0.999
400
random action
action (5, 2, 3)
update weights
0.999
401
random action
s0의 전송이 deadline 안에 완료됨
action (10, 0, 0)
update weights
source 0 전송완료
source 1 전송완료
source 2 deadine 충족하지 못함
모두 전송 완료
episode end
-----------------
-------------
Episode start 17

ac

update weights
0.999
516
random action
action (5, 3, 2)
update weights
0.999
517
random action
action (0, 6, 4)
update weights
0.999
518
random action
action (6, 0, 4)
update weights
0.999
519
random action
action (4, 3, 3)
update weights
0.999
520
random action
action (1, 2, 7)
update weights
0.999
521
random action
s1의 전송이 deadline을 지나 완료됨
action (0, 9, 1)
update weights
source 0 전송완료
source 1 deadine 충족하지 못함
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 22

action [0, 0, 10]
0.999
522
random action
action (2, 6, 2)
update weights
0.999
523
random action
action (6, 0, 4)
update weights
0.999
524
random action
action (3, 7, 0)
update weights
0.999
525
random action
action (4, 4, 2)
update weights
0.999
526
random action
s2의 전송이 deadline 안에 완료됨
action (0, 5, 5)
update weights
0.999
527
random action
action (5, 0, 5)
update weights
0.999
528
random action
action (2, 6, 2)
update weights
0.999
529
random action
action (0, 7, 3)
update weights
0.999
530


update weights
source 0 deadine 충족하지 못함
source 1 전송완료
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 27

action [0, 10, 0]
0.999
644
random action
action (4, 0, 6)
update weights
0.999
645
random action
action (1, 3, 6)
update weights
0.999
646
random action
action (1, 2, 7)
update weights
0.999
647
random action
action (0, 10, 0)
update weights
0.999
648
random action
action (4, 3, 3)
update weights
0.999
649
random action
action (1, 7, 2)
update weights
0.999
650
random action
s1의 전송이 deadline 안에 완료됨
action (0, 7, 3)
update weights
0.999
651
random action
action (0, 3, 7)
update weights
0.999
652
random action
action (2, 4, 4)
update weights
0.999
653
random action
action (4, 0, 6)
update weights
0.999
654
random action
action (0, 2, 8)
update weights
0.999
655
random action
action (2, 0, 8)
update weights
0.999
656
random action
action (0, 7, 3)
update weights
0.999
657
random action
action (1, 4, 5)
update weights
0.999
658
random action
s2의 전송이 de

update weights
0.999
774
random action
action (1, 5, 4)
update weights
0.999
775
random action
action (0, 7, 3)
update weights
0.999
776
random action
s1의 전송이 deadline 안에 완료됨
action (3, 7, 0)
update weights
0.999
777
random action
s2의 전송이 deadline 안에 완료됨
action (0, 6, 4)
update weights
source 0 전송완료
source 1 전송완료
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 32

action [0, 10, 0]
0.999
778
random action
s1의 전송이 deadline 안에 완료됨
action (0, 10, 0)
update weights
0.999
779
random action
action (3, 7, 0)
update weights
0.999
780
random action
action (5, 3, 2)
update weights
0.999
781
random action
action (0, 4, 6)
update weights
0.999
782
random action
action (8, 0, 2)
update weights
0.999
783
random action
action (3, 1, 6)
update weights
0.999
784
random action
action (2, 7, 1)
update weights
0.999
785
random action
action (3, 7, 0)
update weights
0.999
786
random action
action (3, 1, 6)
update weights
0.999
787
random action
action (9, 1, 0)
update weigh

update weights
0.999
902
random action
action (3, 2, 5)
update weights
0.999
903
random action
s1의 전송이 deadline을 지나 완료됨
action (2, 5, 3)
update weights
source 0 전송완료
source 1 deadine 충족하지 못함
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 37

action [10, 0, 0]
0.999
904
random action
action (2, 1, 7)
update weights
0.999
905
random action
action (4, 4, 2)
update weights
0.999
906
random action
action (7, 2, 1)
update weights
0.999
907
random action
action (0, 5, 5)
update weights
0.999
908
random action
action (2, 3, 5)
update weights
0.999
909
random action
action (0, 9, 1)
update weights
0.999
910
random action
action (4, 0, 6)
update weights
0.999
911
random action
action (0, 0, 10)
update weights
0.999
912
random action
action (8, 1, 1)
update weights
0.999
913
random action
action (3, 7, 0)
update weights
0.999
914
random action
action (2, 5, 3)
update weights
0.999
915
random action
action (5, 5, 0)
update weights
0.999
916
random action
action (3

update weights
0.998001
1029
random action
action (7, 1, 2)
update weights
0.998001
1030
random action
s0의 전송이 deadline 안에 완료됨
action (7, 0, 3)
update weights
0.998001
1031
random action
action (0, 3, 7)
update weights
0.998001
1032
random action
action (7, 2, 1)
update weights
0.998001
1033
action (3, 6, 1)
update weights
0.998001
1034
random action
action (0, 2, 8)
update weights
0.998001
1035
random action
action (5, 2, 3)
update weights
0.998001
1036
random action
action (0, 1, 9)
update weights
0.998001
1037
random action
s2의 전송이 deadline을 지나 완료됨
action (4, 0, 6)
update weights
source 0 전송완료
source 1 전송완료
source 2 deadine 충족하지 못함
모두 전송 완료
episode end
-----------------
-------------
Episode start 42

action [0, 0, 10]
0.998001
1038
random action
action (4, 2, 4)
update weights
0.998001
1039
random action
action (5, 4, 1)
update weights
0.998001
1040
random action
action (5, 0, 5)
update weights
0.998001
1041
random action
action (1, 4, 5)
update weights
0.998001
1042
random action


update weights
0.998001
1149
random action
s0의 전송이 deadline 안에 완료됨
action (9, 0, 1)
update weights
0.998001
1150
random action
action (4, 5, 1)
update weights
0.998001
1151
random action
action (0, 10, 0)
update weights
0.998001
1152
random action
action (3, 0, 7)
update weights
0.998001
1153
random action
action (3, 1, 6)
update weights
0.998001
1154
random action
action (3, 4, 3)
update weights
0.998001
1155
random action
action (0, 1, 9)
update weights
0.998001
1156
random action
action (3, 4, 3)
update weights
0.998001
1157
random action
action (10, 0, 0)
update weights
0.998001
1158
random action
action (4, 2, 4)
update weights
0.998001
1159
random action
action (2, 2, 6)
update weights
0.998001
1160
random action
action (3, 3, 4)
update weights
0.998001
1161
random action
action (8, 0, 2)
update weights
0.998001
1162
random action
s1의 전송이 deadline을 지나 완료됨
action (0, 9, 1)
update weights
source 0 전송완료
source 1 deadine 충족하지 못함
source 2 전송완료
모두 전송 완료
episode end
-----------------
--

update weights
0.998001
1268
random action
action (5, 0, 5)
update weights
0.998001
1269
random action
action (6, 4, 0)
update weights
0.998001
1270
random action
action (1, 8, 1)
update weights
0.998001
1271
random action
action (4, 3, 3)
update weights
0.998001
1272
random action
action (1, 5, 4)
update weights
0.998001
1273
random action
action (1, 5, 4)
update weights
0.998001
1274
random action
action (1, 2, 7)
update weights
0.998001
1275
random action
s1의 전송이 deadline을 지나 완료됨
action (3, 7, 0)
update weights
0.998001
1276
random action
action (6, 2, 2)
update weights
0.998001
1277
random action
action (0, 0, 10)
update weights
0.998001
1278
random action
action (5, 3, 2)
update weights
0.998001
1279
random action
action (0, 0, 10)
update weights
0.998001
1280
random action
action (2, 7, 1)
update weights
0.998001
1281
random action
action (1, 3, 6)
update weights
0.998001
1282
random action
action (4, 6, 0)
update weights
0.998001
1283
random action
action (9, 1, 0)
update weight

update weights
source 0 전송완료
source 1 deadine 충족하지 못함
source 2 deadine 충족하지 못함
모두 전송 완료
episode end
-----------------
-------------
Episode start 56

action [0, 0, 10]
0.998001
1390
random action
action (2, 2, 6)
update weights
0.998001
1391
random action
action (2, 2, 6)
update weights
0.998001
1392
random action
action (0, 8, 2)
update weights
0.998001
1393
random action
action (2, 0, 8)
update weights
0.998001
1394
random action
s2의 전송이 deadline 안에 완료됨
action (1, 0, 9)
update weights
0.998001
1395
random action
action (1, 2, 7)
update weights
0.998001
1396
random action
action (0, 8, 2)
update weights
0.998001
1397
random action
action (6, 4, 0)
update weights
0.998001
1398
random action
action (2, 1, 7)
update weights
0.998001
1399
random action
action (7, 3, 0)
update weights
0.998001
1400
random action
action (1, 6, 3)
update weights
0.998001
1401
random action
action (4, 0, 6)
update weights
0.998001
1402
random action
action (4, 4, 2)
update weights
0.998001
1403
random action


update weights
0.998001
1510
random action
action (5, 0, 5)
update weights
0.998001
1511
random action
action (2, 3, 5)
update weights
0.998001
1512
random action
action (0, 6, 4)
update weights
0.998001
1513
random action
action (8, 0, 2)
update weights
0.998001
1514
random action
action (2, 3, 5)
update weights
0.998001
1515
random action
action (5, 0, 5)
update weights
0.998001
1516
random action
action (4, 4, 2)
update weights
0.998001
1517
random action
action (4, 1, 5)
update weights
0.998001
1518
random action
action (3, 7, 0)
update weights
0.998001
1519
random action
action (1, 9, 0)
update weights
0.998001
1520
random action
action (0, 10, 0)
update weights
0.998001
1521
random action
s2의 전송이 deadline을 지나 완료됨
action (2, 1, 7)
update weights
source 0 전송완료
source 1 전송완료
source 2 deadine 충족하지 못함
모두 전송 완료
episode end
-----------------
-------------
Episode start 61

action [10, 0, 0]
0.998001
1522
random action
action (1, 3, 6)
update weights
0.998001
1523
random action
action (3

update weights
0.998001
1633
random action
action (8, 1, 1)
update weights
0.998001
1634
random action
action (6, 4, 0)
update weights
0.998001
1635
random action
action (1, 9, 0)
update weights
0.998001
1636
random action
action (9, 1, 0)
update weights
0.998001
1637
random action
action (1, 1, 8)
update weights
0.998001
1638
random action
action (3, 3, 4)
update weights
0.998001
1639
random action
action (2, 3, 5)
update weights
0.998001
1640
random action
s2의 전송이 deadline 안에 완료됨
action (2, 1, 7)
update weights
0.998001
1641
random action
action (2, 4, 4)
update weights
0.998001
1642
random action
action (4, 1, 5)
update weights
0.998001
1643
random action
action (8, 0, 2)
update weights
0.998001
1644
random action
action (6, 4, 0)
update weights
0.998001
1645
random action
action (1, 7, 2)
update weights
0.998001
1646
random action
action (3, 4, 3)
update weights
0.998001
1647
random action
action (3, 4, 3)
update weights
0.998001
1648
random action
action (6, 1, 3)
update weights
0

update weights
0.998001
1756
random action
action (2, 0, 8)
update weights
0.998001
1757
random action
action (7, 0, 3)
update weights
0.998001
1758
random action
action (3, 5, 2)
update weights
0.998001
1759
random action
action (1, 9, 0)
update weights
0.998001
1760
random action
action (0, 2, 8)
update weights
0.998001
1761
random action
action (8, 0, 2)
update weights
0.998001
1762
random action
action (4, 1, 5)
update weights
0.998001
1763
random action
action (7, 2, 1)
update weights
0.998001
1764
random action
action (1, 7, 2)
update weights
0.998001
1765
random action
s2의 전송이 deadline 안에 완료됨
action (1, 5, 4)
update weights
0.998001
1766
random action
action (0, 2, 8)
update weights
0.998001
1767
random action
s0의 전송이 deadline 안에 완료됨
action (8, 2, 0)
update weights
source 0 전송완료
source 1 전송완료
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 70

action [0, 10, 0]
0.998001
1768
random action
action (0, 10, 0)
update weights
0.998001
1769
random acti

update weights
0.998001
1876
random action
action (1, 6, 3)
update weights
0.998001
1877
random action
action (4, 2, 4)
update weights
0.998001
1878
random action
action (2, 0, 8)
update weights
0.998001
1879
random action
action (7, 3, 0)
update weights
0.998001
1880
random action
s1의 전송이 deadline 안에 완료됨
action (0, 10, 0)
update weights
0.998001
1881
random action
s2의 전송이 deadline 안에 완료됨
action (0, 2, 8)
update weights
0.998001
1882
random action
action (4, 5, 1)
update weights
0.998001
1883
random action
s0의 전송이 deadline 안에 완료됨
action (4, 2, 4)
update weights
source 0 전송완료
source 1 전송완료
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 75

action [0, 10, 0]
0.998001
1884
random action
action (2, 6, 2)
update weights
0.998001
1885
random action
action (4, 0, 6)
update weights
0.998001
1886
action (0, 3, 7)
update weights
0.998001
1887
random action
action (3, 7, 0)
update weights
0.998001
1888
random action
s1의 전송이 deadline 안에 완료됨
action (2, 8, 0)
update

update weights
source 0 전송완료
source 1 deadine 충족하지 못함
source 2 deadine 충족하지 못함
모두 전송 완료
episode end
-----------------
-------------
Episode start 80

action [0, 0, 10]
0.998001
1994
random action
action (0, 0, 10)
update weights
0.998001
1995
random action
action (5, 1, 4)
update weights
0.998001
1996
random action
action (3, 7, 0)
update weights
0.998001
1997
random action
action (7, 3, 0)
update weights
0.998001
1998
random action
action (1, 6, 3)
update weights
0.998001
1999
random action
action (6, 2, 2)
update weights
0.9940149800149941
2000
random action
action (2, 3, 5)
update weights
0.9940149800149941
2001
random action
action (2, 2, 6)
update weights
0.9940149800149941
2002
random action
action (4, 2, 4)
update weights
0.9940149800149941
2003
random action
action (2, 2, 6)
update weights
0.9940149800149941
2004
random action
s2의 전송이 deadline 안에 완료됨
action (5, 0, 5)
update weights
0.9940149800149941
2005
random action
action (6, 0, 4)
update weights
0.9940149800149941
2006
ran

update weights
0.9940149800149941
2102
random action
action (0, 3, 7)
update weights
0.9940149800149941
2103
random action
action (7, 2, 1)
update weights
0.9940149800149941
2104
random action
s2의 전송이 deadline을 지나 완료됨
action (2, 2, 6)
update weights
source 0 전송완료
source 1 전송완료
source 2 deadine 충족하지 못함
모두 전송 완료
episode end
-----------------
-------------
Episode start 84

action [10, 0, 0]
0.9940149800149941
2105
random action
action (7, 2, 1)
update weights
0.9940149800149941
2106
random action
action (0, 4, 6)
update weights
0.9940149800149941
2107
random action
action (9, 0, 1)
update weights
0.9940149800149941
2108
random action
action (2, 3, 5)
update weights
0.9940149800149941
2109
random action
action (4, 3, 3)
update weights
0.9940149800149941
2110
random action
s0의 전송이 deadline 안에 완료됨
action (6, 2, 2)
update weights
0.9940149800149941
2111
random action
action (6, 4, 0)
update weights
0.9940149800149941
2112
random action
action (4, 5, 1)
update weights
0.9940149800149941
2113


update weights
0.9940149800149941
2207
random action
s2의 전송이 deadline을 지나 완료됨
action (2, 2, 6)
update weights
0.9940149800149941
2208
random action
action (1, 5, 4)
update weights
0.9940149800149941
2209
random action
action (0, 6, 4)
update weights
0.9940149800149941
2210
random action
s0의 전송이 deadline 안에 완료됨
action (6, 2, 2)
update weights
source 0 전송완료
source 1 전송완료
source 2 deadine 충족하지 못함
모두 전송 완료
episode end
-----------------
-------------
Episode start 88

action [0, 0, 10]
0.9940149800149941
2211
random action
action (8, 1, 1)
update weights
0.9940149800149941
2212
action (0, 3, 7)
update weights
0.9940149800149941
2213
random action
action (9, 1, 0)
update weights
0.9940149800149941
2214
random action
action (4, 2, 4)
update weights
0.9940149800149941
2215
random action
s2의 전송이 deadline 안에 완료됨
action (3, 6, 1)
update weights
0.9940149800149941
2216
random action
action (1, 7, 2)
update weights
0.9940149800149941
2217
random action
action (0, 8, 2)
update weights
0.994014980014

update weights
0.9940149800149941
2313
random action
s0의 전송이 deadline 안에 완료됨
action (4, 4, 2)
update weights
0.9940149800149941
2314
random action
action (8, 2, 0)
update weights
0.9940149800149941
2315
action (0, 3, 7)
update weights
0.9940149800149941
2316
random action
action (3, 7, 0)
update weights
0.9940149800149941
2317
random action
action (8, 2, 0)
update weights
0.9940149800149941
2318
random action
action (0, 1, 9)
update weights
0.9940149800149941
2319
random action
action (5, 2, 3)
update weights
0.9940149800149941
2320
random action
action (6, 0, 4)
update weights
0.9940149800149941
2321
random action
action (2, 5, 3)
update weights
0.9940149800149941
2322
random action
action (6, 3, 1)
update weights
0.9940149800149941
2323
random action
action (4, 6, 0)
update weights
0.9940149800149941
2324
random action
action (8, 1, 1)
update weights
0.9940149800149941
2325
random action
action (3, 3, 4)
update weights
0.9940149800149941
2326
random action
action (2, 4, 4)
update wei

update weights
0.9940149800149941
2422
random action
s0의 전송이 deadline 안에 완료됨
action (9, 1, 0)
update weights
0.9940149800149941
2423
random action
s2의 전송이 deadline을 지나 완료됨
action (0, 4, 6)
update weights
source 0 전송완료
source 1 전송완료
source 2 deadine 충족하지 못함
모두 전송 완료
episode end
-----------------
-------------
Episode start 95

action [0, 10, 0]
0.9940149800149941
2424
random action
action (2, 4, 4)
update weights
0.9940149800149941
2425
random action
action (1, 3, 6)
update weights
0.9940149800149941
2426
random action
action (7, 2, 1)
update weights
0.9940149800149941
2427
random action
action (3, 3, 4)
update weights
0.9940149800149941
2428
random action
action (2, 5, 3)
update weights
0.9940149800149941
2429
random action
action (7, 2, 1)
update weights
0.9940149800149941
2430
random action
action (8, 2, 0)
update weights
0.9940149800149941
2431
random action
action (0, 1, 9)
update weights
0.9940149800149941
2432
random action
action (5, 3, 2)
update weights
0.9940149800149941
2433


update weights
0.9940149800149941
2528
random action
action (3, 3, 4)
update weights
0.9940149800149941
2529
random action
action (6, 3, 1)
update weights
0.9940149800149941
2530
random action
action (9, 1, 0)
update weights
0.9940149800149941
2531
random action
action (0, 6, 4)
update weights
0.9940149800149941
2532
random action
action (0, 1, 9)
update weights
0.9940149800149941
2533
random action
action (1, 1, 8)
update weights
0.9940149800149941
2534
random action
action (8, 1, 1)
update weights
0.9940149800149941
2535
random action
s2의 전송이 deadline 안에 완료됨
action (5, 1, 4)
update weights
source 0 deadine 충족하지 못함
source 1 전송완료
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 99

action [10, 0, 0]
0.9940149800149941
2536
random action
action (0, 2, 8)
update weights
0.9940149800149941
2537
random action
action (0, 9, 1)
update weights
0.9940149800149941
2538
random action
action (6, 0, 4)
update weights
0.9940149800149941
2539
random action
action (0, 

update weights
0.9940149800149941
2634
random action
action (0, 0, 10)
update weights
0.9940149800149941
2635
random action
action (1, 8, 1)
update weights
0.9940149800149941
2636
random action
s1의 전송이 deadline 안에 완료됨
action (4, 5, 1)
update weights
0.9940149800149941
2637
random action
action (0, 9, 1)
update weights
0.9940149800149941
2638
random action
action (0, 9, 1)
update weights
0.9940149800149941
2639
random action
action (0, 8, 2)
update weights
0.9940149800149941
2640
random action
action (1, 0, 9)
update weights
0.9940149800149941
2641
random action
action (5, 1, 4)
update weights
0.9940149800149941
2642
random action
action (1, 9, 0)
update weights
0.9940149800149941
2643
random action
action (6, 4, 0)
update weights
0.9940149800149941
2644
random action
action (5, 0, 5)
update weights
0.9940149800149941
2645
random action
action (5, 5, 0)
update weights
0.9940149800149941
2646
random action
action (7, 2, 1)
update weights
0.9940149800149941
2647
random action
action (3, 0

update weights
0.9940149800149941
2740
random action
action (3, 2, 5)
update weights
0.9940149800149941
2741
random action
action (4, 1, 5)
update weights
0.9940149800149941
2742
random action
action (7, 2, 1)
update weights
0.9940149800149941
2743
random action
action (6, 3, 1)
update weights
0.9940149800149941
2744
random action
action (5, 5, 0)
update weights
0.9940149800149941
2745
random action
action (0, 3, 7)
update weights
0.9940149800149941
2746
random action
action (5, 5, 0)
update weights
0.9940149800149941
2747
random action
action (4, 5, 1)
update weights
0.9940149800149941
2748
random action
action (3, 7, 0)
update weights
0.9940149800149941
2749
random action
action (4, 2, 4)
update weights
0.9940149800149941
2750
random action
action (8, 2, 0)
update weights
0.9940149800149941
2751
random action
action (4, 2, 4)
update weights
0.9940149800149941
2752
random action
s0의 전송이 deadline 안에 완료됨
action (8, 0, 2)
update weights
0.9940149800149941
2753
random action
action (3, 1,

update weights
0.9940149800149941
2846
random action
action (2, 1, 7)
update weights
0.9940149800149941
2847
random action
action (2, 1, 7)
update weights
0.9940149800149941
2848
random action
action (9, 1, 0)
update weights
0.9940149800149941
2849
random action
action (7, 1, 2)
update weights
0.9940149800149941
2850
random action
action (9, 0, 1)
update weights
0.9940149800149941
2851
random action
action (5, 1, 4)
update weights
0.9940149800149941
2852
random action
action (5, 4, 1)
update weights
0.9940149800149941
2853
random action
action (8, 2, 0)
update weights
0.9940149800149941
2854
random action
action (4, 4, 2)
update weights
0.9940149800149941
2855
random action
action (8, 2, 0)
update weights
0.9940149800149941
2856
random action
action (6, 4, 0)
update weights
0.9940149800149941
2857
random action
action (0, 3, 7)
update weights
0.9940149800149941
2858
random action
s2의 전송이 deadline 안에 완료됨
action (3, 0, 7)
update weights
source 0 전송완료
source 1 전송완료
source 2 전송완료
모두 전송 완료


update weights
0.9940149800149941
2952
random action
action (3, 2, 5)
update weights
0.9940149800149941
2953
random action
action (7, 0, 3)
update weights
0.9940149800149941
2954
random action
action (7, 0, 3)
update weights
0.9940149800149941
2955
random action
s1의 전송이 deadline을 지나 완료됨
action (1, 6, 3)
update weights
0.9940149800149941
2956
random action
action (1, 5, 4)
update weights
0.9940149800149941
2957
random action
action (0, 1, 9)
update weights
0.9940149800149941
2958
random action
action (4, 0, 6)
update weights
0.9940149800149941
2959
random action
action (3, 3, 4)
update weights
0.9940149800149941
2960
random action
action (0, 7, 3)
update weights
0.9940149800149941
2961
random action
action (7, 2, 1)
update weights
0.9940149800149941
2962
random action
action (8, 0, 2)
update weights
0.9940149800149941
2963
random action
action (1, 0, 9)
update weights
0.9940149800149941
2964
random action
action (8, 2, 0)
update weights
0.9940149800149941
2965
random action
action (9, 0

update weights
0.9762739865836306
3061
random action
action (4, 4, 2)
update weights
0.9762739865836306
3062
random action
action (0, 4, 6)
update weights
0.9762739865836306
3063
random action
action (3, 0, 7)
update weights
0.9762739865836306
3064
random action
action (1, 1, 8)
update weights
0.9762739865836306
3065
random action
s2의 전송이 deadline 안에 완료됨
action (3, 1, 6)
update weights
0.9762739865836306
3066
random action
action (6, 2, 2)
update weights
0.9762739865836306
3067
random action
action (1, 0, 9)
update weights
0.9762739865836306
3068
random action
action (2, 0, 8)
update weights
0.9762739865836306
3069
random action
action (0, 1, 9)
update weights
0.9762739865836306
3070
random action
action (3, 3, 4)
update weights
0.9762739865836306
3071
random action
action (5, 1, 4)
update weights
0.9762739865836306
3072
random action
action (0, 2, 8)
update weights
0.9762739865836306
3073
random action
action (6, 4, 0)
update weights
0.9762739865836306
3074
random action
action (4, 6,

update weights
0.9762739865836306
3170
random action
action (2, 4, 4)
update weights
0.9762739865836306
3171
action (0, 2, 8)
update weights
0.9762739865836306
3172
random action
action (1, 3, 6)
update weights
0.9762739865836306
3173
random action
action (3, 6, 1)
update weights
0.9762739865836306
3174
random action
action (9, 0, 1)
update weights
0.9762739865836306
3175
random action
action (5, 3, 2)
update weights
0.9762739865836306
3176
random action
s0의 전송이 deadline 안에 완료됨
action (4, 3, 3)
update weights
0.9762739865836306
3177
random action
s1의 전송이 deadline 안에 완료됨
action (9, 1, 0)
update weights
source 0 전송완료
source 1 전송완료
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 122

action [10, 0, 0]
0.9762739865836306
3178
random action
action (1, 9, 0)
update weights
0.9762739865836306
3179
random action
action (3, 6, 1)
update weights
0.9762739865836306
3180
random action
action (4, 5, 1)
update weights
0.9762739865836306
3181
random action
action (4, 

update weights
0.9762739865836306
3276
random action
action (1, 4, 5)
update weights
0.9762739865836306
3277
random action
action (6, 4, 0)
update weights
0.9762739865836306
3278
random action
action (0, 2, 8)
update weights
0.9762739865836306
3279
random action
action (0, 7, 3)
update weights
0.9762739865836306
3280
random action
action (0, 5, 5)
update weights
0.9762739865836306
3281
random action
action (5, 2, 3)
update weights
0.9762739865836306
3282
random action
action (3, 1, 6)
update weights
0.9762739865836306
3283
random action
action (5, 4, 1)
update weights
0.9762739865836306
3284
random action
action (1, 2, 7)
update weights
0.9762739865836306
3285
random action
s1의 전송이 deadline 안에 완료됨
action (2, 8, 0)
update weights
0.9762739865836306
3286
random action
action (1, 1, 8)
update weights
0.9762739865836306
3287
random action
s2의 전송이 deadline 안에 완료됨
action (0, 9, 1)
update weights
0.9762739865836306
3288
random action
action (5, 0, 5)
update weights
0.9762739865836306
3289
ran

update weights
0.9762739865836306
3381
random action
action (2, 8, 0)
update weights
0.9762739865836306
3382
random action
action (2, 8, 0)
update weights
0.9762739865836306
3383
random action
action (5, 0, 5)
update weights
0.9762739865836306
3384
random action
action (4, 6, 0)
update weights
0.9762739865836306
3385
random action
action (0, 7, 3)
update weights
0.9762739865836306
3386
random action
action (5, 5, 0)
update weights
0.9762739865836306
3387
random action
action (1, 5, 4)
update weights
0.9762739865836306
3388
random action
s1의 전송이 deadline 안에 완료됨
action (4, 6, 0)
update weights
0.9762739865836306
3389
random action
action (5, 3, 2)
update weights
0.9762739865836306
3390
random action
action (0, 8, 2)
update weights
0.9762739865836306
3391
random action
action (5, 5, 0)
update weights
0.9762739865836306
3392
random action
action (5, 1, 4)
update weights
0.9762739865836306
3393
random action
action (1, 3, 6)
update weights
0.9762739865836306
3394
random action
s0의 전송이 deadl

update weights
0.9762739865836306
3488
random action
action (8, 2, 0)
update weights
0.9762739865836306
3489
random action
action (6, 2, 2)
update weights
0.9762739865836306
3490
action (1, 0, 9)
update weights
0.9762739865836306
3491
random action
action (3, 4, 3)
update weights
0.9762739865836306
3492
random action
action (3, 5, 2)
update weights
0.9762739865836306
3493
random action
action (2, 2, 6)
update weights
0.9762739865836306
3494
random action
s1의 전송이 deadline 안에 완료됨
action (3, 7, 0)
update weights
0.9762739865836306
3495
random action
s0의 전송이 deadline 안에 완료됨
action (4, 5, 1)
update weights
source 0 전송완료
source 1 전송완료
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 135

action [0, 10, 0]
0.9762739865836306
3496
random action
action (0, 7, 3)
update weights
0.9762739865836306
3497
random action
s1의 전송이 deadline 안에 완료됨
action (1, 6, 3)
update weights
0.9762739865836306
3498
random action
action (6, 1, 3)
update weights
0.9762739865836306
3499
r

update weights
0.9762739865836306
3595
random action
action (3, 0, 7)
update weights
0.9762739865836306
3596
random action
action (7, 0, 3)
update weights
0.9762739865836306
3597
random action
action (2, 8, 0)
update weights
0.9762739865836306
3598
random action
action (0, 7, 3)
update weights
0.9762739865836306
3599
random action
action (1, 1, 8)
update weights
0.9762739865836306
3600
random action
action (0, 4, 6)
update weights
0.9762739865836306
3601
random action
action (9, 0, 1)
update weights
0.9762739865836306
3602
random action
action (0, 6, 4)
update weights
0.9762739865836306
3603
random action
action (3, 6, 1)
update weights
0.9762739865836306
3604
random action
action (4, 3, 3)
update weights
0.9762739865836306
3605
random action
action (1, 5, 4)
update weights
0.9762739865836306
3606
random action
action (0, 0, 10)
update weights
0.9762739865836306
3607
random action
action (2, 1, 7)
update weights
0.9762739865836306
3608
random action
action (4, 5, 1)
update weights
0.97

update weights
0.9762739865836306
3702
random action
action (5, 1, 4)
update weights
0.9762739865836306
3703
random action
action (5, 5, 0)
update weights
0.9762739865836306
3704
random action
s2의 전송이 deadline 안에 완료됨
action (1, 0, 9)
update weights
0.9762739865836306
3705
random action
action (2, 2, 6)
update weights
0.9762739865836306
3706
random action
action (9, 0, 1)
update weights
0.9762739865836306
3707
random action
action (5, 5, 0)
update weights
0.9762739865836306
3708
random action
action (4, 0, 6)
update weights
0.9762739865836306
3709
random action
action (3, 7, 0)
update weights
0.9762739865836306
3710
random action
action (0, 9, 1)
update weights
0.9762739865836306
3711
random action
action (4, 5, 1)
update weights
0.9762739865836306
3712
random action
action (1, 7, 2)
update weights
0.9762739865836306
3713
random action
action (6, 0, 4)
update weights
0.9762739865836306
3714
random action
action (3, 7, 0)
update weights
0.9762739865836306
3715
random action
action (1, 5,

update weights
0.9762739865836306
3808
random action
action (1, 1, 8)
update weights
0.9762739865836306
3809
random action
s0의 전송이 deadline을 지나 완료됨
action (2, 7, 1)
update weights
0.9762739865836306
3810
random action
s2의 전송이 deadline을 지나 완료됨
action (1, 4, 5)
update weights
0.9762739865836306
3811
random action
s1의 전송이 deadline 안에 완료됨
action (3, 6, 1)
update weights
source 0 deadine 충족하지 못함
source 1 전송완료
source 2 deadine 충족하지 못함
모두 전송 완료
episode end
-----------------
-------------
Episode start 148

action [0, 0, 10]
0.9762739865836306
3812
random action
action (1, 9, 0)
update weights
0.9762739865836306
3813
random action
action (1, 7, 2)
update weights
0.9762739865836306
3814
random action
action (5, 5, 0)
update weights
0.9762739865836306
3815
random action
action (8, 2, 0)
update weights
0.9762739865836306
3816
random action
action (4, 1, 5)
update weights
0.9762739865836306
3817
random action
action (5, 1, 4)
update weights
0.9762739865836306
3818
random action
action (0, 4, 6)
up

update weights
source 0 deadine 충족하지 못함
source 1 deadine 충족하지 못함
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 152

action [10, 0, 0]
0.9762739865836306
3914
random action
action (0, 0, 10)
update weights
0.9762739865836306
3915
random action
action (0, 4, 6)
update weights
0.9762739865836306
3916
random action
action (2, 0, 8)
update weights
0.9762739865836306
3917
random action
action (6, 3, 1)
update weights
0.9762739865836306
3918
random action
action (0, 4, 6)
update weights
0.9762739865836306
3919
random action
action (3, 0, 7)
update weights
0.9762739865836306
3920
random action
action (6, 1, 3)
update weights
0.9762739865836306
3921
random action
action (0, 7, 3)
update weights
0.9762739865836306
3922
random action
action (1, 7, 2)
update weights
0.9762739865836306
3923
random action
action (6, 3, 1)
update weights
0.9762739865836306
3924
random action
action (1, 5, 4)
update weights
0.9762739865836306
3925
random action
action (1, 4, 5)
updat

0.8868671875860655
4017
random action
s0의 전송이 deadline 안에 완료됨
s1의 전송이 deadline을 지나 완료됨
action (2, 5, 3)
update weights
0.8868671875860655
4018
random action
action (4, 0, 6)
update weights
0.8868671875860655
4019
random action
action (3, 1, 6)
update weights
0.8868671875860655
4020
random action
action (7, 3, 0)
update weights
0.8868671875860655
4021
random action
action (1, 5, 4)
update weights
0.8868671875860655
4022
random action
action (3, 5, 2)
update weights
0.8868671875860655
4023
random action
s2의 전송이 deadline 안에 완료됨
action (5, 0, 5)
update weights
source 0 전송완료
source 1 deadine 충족하지 못함
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 157

action [0, 0, 10]
0.8868671875860655
4024
random action
action (1, 1, 8)
update weights
0.8868671875860655
4025
random action
action (3, 4, 3)
update weights
0.8868671875860655
4026
random action
action (1, 0, 9)
update weights
0.8868671875860655
4027
random action
action (0, 1, 9)
update weights
0.886867187586

update weights
0.8868671875860655
4125
random action
action (7, 3, 0)
update weights
0.8868671875860655
4126
random action
action (0, 1, 9)
update weights
0.8868671875860655
4127
random action
action (2, 4, 4)
update weights
0.8868671875860655
4128
random action
action (2, 7, 1)
update weights
0.8868671875860655
4129
random action
action (3, 4, 3)
update weights
0.8868671875860655
4130
random action
action (7, 2, 1)
update weights
0.8868671875860655
4131
random action
action (6, 0, 4)
update weights
0.8868671875860655
4132
random action
action (0, 0, 10)
update weights
0.8868671875860655
4133
random action
action (0, 1, 9)
update weights
0.8868671875860655
4134
action (1, 0, 9)
update weights
0.8868671875860655
4135
random action
action (7, 3, 0)
update weights
0.8868671875860655
4136
random action
action (5, 2, 3)
update weights
0.8868671875860655
4137
random action
s1의 전송이 deadline을 지나 완료됨
action (0, 10, 0)
update weights
0.8868671875860655
4138
random action
action (0, 2, 8)
update 

update weights
0.8868671875860655
4233
random action
action (0, 1, 9)
update weights
0.8868671875860655
4234
random action
action (0, 1, 9)
update weights
0.8868671875860655
4235
random action
action (5, 0, 5)
update weights
0.8868671875860655
4236
random action
s0의 전송이 deadline을 지나 완료됨
action (4, 2, 4)
update weights
0.8868671875860655
4237
random action
action (3, 6, 1)
update weights
0.8868671875860655
4238
random action
s2의 전송이 deadline 안에 완료됨
action (0, 5, 5)
update weights
source 0 deadine 충족하지 못함
source 1 전송완료
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 165

action [10, 0, 0]
0.8868671875860655
4239
random action
action (0, 5, 5)
update weights
0.8868671875860655
4240
random action
action (1, 5, 4)
update weights
0.8868671875860655
4241
random action
action (6, 0, 4)
update weights
0.8868671875860655
4242
random action
action (4, 6, 0)
update weights
0.8868671875860655
4243
random action
action (2, 0, 8)
update weights
0.8868671875860655
4244

update weights
0.8868671875860655
4340
action (1, 0, 9)
update weights
0.8868671875860655
4341
random action
action (1, 4, 5)
update weights
0.8868671875860655
4342
action (1, 0, 9)
update weights
0.8868671875860655
4343
random action
s2의 전송이 deadline 안에 완료됨
action (6, 1, 3)
update weights
0.8868671875860655
4344
random action
action (3, 4, 3)
update weights
0.8868671875860655
4345
random action
action (1, 0, 9)
update weights
0.8868671875860655
4346
random action
action (5, 0, 5)
update weights
0.8868671875860655
4347
random action
action (5, 3, 2)
update weights
0.8868671875860655
4348
random action
action (10, 0, 0)
update weights
0.8868671875860655
4349
random action
action (2, 6, 2)
update weights
0.8868671875860655
4350
random action
action (6, 0, 4)
update weights
0.8868671875860655
4351
random action
action (0, 4, 6)
update weights
0.8868671875860655
4352
random action
action (0, 2, 8)
update weights
0.8868671875860655
4353
random action
action (4, 5, 1)
update weights
0.886867

update weights
0.8868671875860655
4448
random action
action (1, 9, 0)
update weights
0.8868671875860655
4449
action (1, 0, 9)
update weights
0.8868671875860655
4450
action (1, 0, 9)
update weights
0.8868671875860655
4451
random action
action (0, 4, 6)
update weights
0.8868671875860655
4452
random action
action (3, 0, 7)
update weights
0.8868671875860655
4453
random action
action (3, 2, 5)
update weights
0.8868671875860655
4454
random action
action (0, 8, 2)
update weights
0.8868671875860655
4455
random action
action (6, 2, 2)
update weights
0.8868671875860655
4456
random action
action (3, 7, 0)
update weights
0.8868671875860655
4457
s2의 전송이 deadline 안에 완료됨
action (1, 0, 9)
update weights
0.8868671875860655
4458
action (1, 0, 9)
update weights
0.8868671875860655
4459
random action
action (0, 8, 2)
update weights
0.8868671875860655
4460
random action
s1의 전송이 deadline을 지나 완료됨
action (1, 2, 7)
update weights
source 0 전송완료
source 1 deadine 충족하지 못함
source 2 전송완료
모두 전송 완료
episode end
--------

update weights
0.8868671875860655
4554
random action
action (4, 3, 3)
update weights
0.8868671875860655
4555
action (1, 0, 9)
update weights
0.8868671875860655
4556
random action
action (0, 4, 6)
update weights
0.8868671875860655
4557
random action
action (2, 8, 0)
update weights
0.8868671875860655
4558
random action
action (6, 1, 3)
update weights
0.8868671875860655
4559
random action
action (2, 0, 8)
update weights
0.8868671875860655
4560
random action
action (7, 1, 2)
update weights
0.8868671875860655
4561
random action
action (6, 2, 2)
update weights
0.8868671875860655
4562
random action
action (5, 2, 3)
update weights
0.8868671875860655
4563
random action
action (2, 0, 8)
update weights
0.8868671875860655
4564
action (1, 0, 9)
update weights
0.8868671875860655
4565
random action
action (2, 6, 2)
update weights
0.8868671875860655
4566
random action
action (5, 4, 1)
update weights
0.8868671875860655
4567
random action
s0의 전송이 deadline 안에 완료됨
action (7, 3, 0)
update weights
0.8868671

update weights
0.8868671875860655
4661
random action
action (3, 3, 4)
update weights
0.8868671875860655
4662
random action
action (10, 0, 0)
update weights
0.8868671875860655
4663
random action
action (0, 4, 6)
update weights
0.8868671875860655
4664
random action
action (1, 9, 0)
update weights
0.8868671875860655
4665
random action
action (3, 3, 4)
update weights
0.8868671875860655
4666
random action
action (4, 1, 5)
update weights
0.8868671875860655
4667
random action
action (2, 1, 7)
update weights
0.8868671875860655
4668
random action
s1의 전송이 deadline 안에 완료됨
action (1, 7, 2)
update weights
0.8868671875860655
4669
random action
action (7, 2, 1)
update weights
0.8868671875860655
4670
random action
action (6, 2, 2)
update weights
0.8868671875860655
4671
action (1, 0, 9)
update weights
0.8868671875860655
4672
random action
action (3, 5, 2)
update weights
0.8868671875860655
4673
random action
action (9, 1, 0)
update weights
0.8868671875860655
4674
random action
s0의 전송이 deadline 안에 완료됨
ac

update weights
source 0 전송완료
source 1 deadine 충족하지 못함
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 185

action [0, 10, 0]
0.8868671875860655
4771
random action
action (2, 7, 1)
update weights
0.8868671875860655
4772
random action
action (0, 4, 6)
update weights
0.8868671875860655
4773
random action
action (9, 0, 1)
update weights
0.8868671875860655
4774
random action
action (1, 7, 2)
update weights
0.8868671875860655
4775
action (1, 0, 9)
update weights
0.8868671875860655
4776
random action
action (4, 1, 5)
update weights
0.8868671875860655
4777
random action
action (5, 5, 0)
update weights
0.8868671875860655
4778
random action
action (7, 2, 1)
update weights
0.8868671875860655
4779
random action
action (3, 2, 5)
update weights
0.8868671875860655
4780
random action
action (3, 7, 0)
update weights
0.8868671875860655
4781
action (1, 0, 9)
update weights
0.8868671875860655
4782
action (1, 0, 9)
update weights
0.8868671875860655
4783
random action
action

update weights
0.8868671875860655
4876
random action
action (10, 0, 0)
update weights
0.8868671875860655
4877
random action
action (1, 5, 4)
update weights
0.8868671875860655
4878
random action
action (5, 5, 0)
update weights
0.8868671875860655
4879
random action
action (1, 5, 4)
update weights
0.8868671875860655
4880
random action
s1의 전송이 deadline 안에 완료됨
action (5, 5, 0)
update weights
0.8868671875860655
4881
random action
action (1, 6, 3)
update weights
0.8868671875860655
4882
random action
action (3, 4, 3)
update weights
0.8868671875860655
4883
random action
action (3, 6, 1)
update weights
0.8868671875860655
4884
random action
action (1, 7, 2)
update weights
0.8868671875860655
4885
random action
action (7, 2, 1)
update weights
0.8868671875860655
4886
random action
action (6, 0, 4)
update weights
0.8868671875860655
4887
action (1, 0, 9)
update weights
0.8868671875860655
4888
random action
action (4, 6, 0)
update weights
0.8868671875860655
4889
action (1, 0, 9)
update weights
0.886867

update weights
0.8868671875860655
4984
random action
action (2, 2, 6)
update weights
0.8868671875860655
4985
random action
action (3, 5, 2)
update weights
0.8868671875860655
4986
random action
action (3, 3, 4)
update weights
0.8868671875860655
4987
random action
action (7, 0, 3)
update weights
0.8868671875860655
4988
random action
action (2, 4, 4)
update weights
0.8868671875860655
4989
random action
action (0, 6, 4)
update weights
0.8868671875860655
4990
random action
s1의 전송이 deadline을 지나 완료됨
action (6, 4, 0)
update weights
source 0 전송완료
source 1 deadine 충족하지 못함
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 194

action [0, 10, 0]
0.8868671875860655
4991
random action
action (8, 2, 0)
update weights
0.8868671875860655
4992
random action
action (3, 4, 3)
update weights
0.8868671875860655
4993
random action
action (0, 2, 8)
update weights
0.8868671875860655
4994
action (1, 0, 9)
update weights
0.8868671875860655
4995
random action
s1의 전송이 deadline 안에 완료됨

update weights
0.4865769398194597
5098
action (1, 0, 9)
update weights
0.4865769398194597
5099
s2의 전송이 deadline 안에 완료됨
action (1, 0, 9)
update weights
0.4865769398194597
5100
action (1, 0, 9)
update weights
0.4865769398194597
5101
random action
action (5, 2, 3)
update weights
0.4865769398194597
5102
random action
action (4, 0, 6)
update weights
0.4865769398194597
5103
random action
action (2, 4, 4)
update weights
0.4865769398194597
5104
action (1, 0, 9)
update weights
0.4865769398194597
5105
action (1, 0, 9)
update weights
0.4865769398194597
5106
action (1, 0, 9)
update weights
0.4865769398194597
5107
random action
s1의 전송이 deadline을 지나 완료됨
action (1, 9, 0)
update weights
0.4865769398194597
5108
random action
action (0, 2, 8)
update weights
0.4865769398194597
5109
action (1, 0, 9)
update weights
0.4865769398194597
5110
random action
action (7, 3, 0)
update weights
0.4865769398194597
5111
action (1, 0, 9)
update weights
0.4865769398194597
5112
action (1, 0, 9)
update weights
0.4865769398

update weights
0.4865769398194597
5218
random action
s2의 전송이 deadline 안에 완료됨
action (5, 1, 4)
update weights
0.4865769398194597
5219
action (1, 0, 9)
update weights
0.4865769398194597
5220
random action
action (1, 2, 7)
update weights
0.4865769398194597
5221
random action
action (6, 1, 3)
update weights
0.4865769398194597
5222
action (1, 0, 9)
update weights
0.4865769398194597
5223
action (1, 0, 9)
update weights
0.4865769398194597
5224
action (1, 0, 9)
update weights
0.4865769398194597
5225
random action
action (3, 6, 1)
update weights
0.4865769398194597
5226
action (1, 0, 9)
update weights
0.4865769398194597
5227
action (1, 0, 9)
update weights
0.4865769398194597
5228
random action
action (0, 3, 7)
update weights
0.4865769398194597
5229
s0의 전송이 deadline을 지나 완료됨
action (1, 0, 9)
update weights
0.4865769398194597
5230
random action
action (0, 3, 7)
update weights
0.4865769398194597
5231
random action
action (4, 6, 0)
update weights
0.4865769398194597
5232
action (1, 0, 9)
update weight

update weights
0.4865769398194597
5340
action (1, 0, 9)
update weights
0.4865769398194597
5341
random action
s1의 전송이 deadline을 지나 완료됨
action (0, 9, 1)
update weights
source 0 전송완료
source 1 deadine 충족하지 못함
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 204

action [10, 0, 0]
0.4865769398194597
5342
random action
action (1, 1, 8)
update weights
0.4865769398194597
5343
random action
action (7, 1, 2)
update weights
0.4865769398194597
5344
random action
action (3, 5, 2)
update weights
0.4865769398194597
5345
action (1, 0, 9)
update weights
0.4865769398194597
5346
random action
action (7, 3, 0)
update weights
0.4865769398194597
5347
action (1, 0, 9)
update weights
0.4865769398194597
5348
action (1, 0, 9)
update weights
0.4865769398194597
5349
action (1, 0, 9)
update weights
0.4865769398194597
5350
random action
action (0, 10, 0)
update weights
0.4865769398194597
5351
random action
action (0, 6, 4)
update weights
0.4865769398194597
5352
random action
action (

update weights
0.4865769398194597
5458
random action
action (1, 4, 5)
update weights
0.4865769398194597
5459
random action
action (7, 2, 1)
update weights
0.4865769398194597
5460
random action
action (2, 6, 2)
update weights
0.4865769398194597
5461
random action
s0의 전송이 deadline을 지나 완료됨
action (5, 2, 3)
update weights
0.4865769398194597
5462
random action
s1의 전송이 deadline을 지나 완료됨
action (2, 2, 6)
update weights
source 0 deadine 충족하지 못함
source 1 deadine 충족하지 못함
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 208

action [0, 10, 0]
0.4865769398194597
5463
random action
action (1, 1, 8)
update weights
0.4865769398194597
5464
random action
action (6, 4, 0)
update weights
0.4865769398194597
5465
random action
action (1, 7, 2)
update weights
0.4865769398194597
5466
action (1, 0, 9)
update weights
0.4865769398194597
5467
random action
s1의 전송이 deadline 안에 완료됨
action (1, 1, 8)
update weights
0.4865769398194597
5468
random action
action (1, 3, 6)
update weights
0

update weights
0.4865769398194597
5578
random action
action (0, 7, 3)
update weights
0.4865769398194597
5579
action (1, 0, 9)
update weights
0.4865769398194597
5580
action (1, 0, 9)
update weights
0.4865769398194597
5581
action (1, 0, 9)
update weights
0.4865769398194597
5582
action (1, 0, 9)
update weights
0.4865769398194597
5583
action (1, 0, 9)
update weights
0.4865769398194597
5584
action (1, 0, 9)
update weights
0.4865769398194597
5585
action (1, 0, 9)
update weights
0.4865769398194597
5586
random action
action (0, 3, 7)
update weights
0.4865769398194597
5587
action (1, 0, 9)
update weights
0.4865769398194597
5588
action (1, 0, 9)
update weights
0.4865769398194597
5589
random action
action (9, 0, 1)
update weights
0.4865769398194597
5590
action (1, 0, 9)
update weights
0.4865769398194597
5591
action (1, 0, 9)
update weights
0.4865769398194597
5592
random action
action (0, 4, 6)
update weights
0.4865769398194597
5593
action (1, 0, 9)
update weights
0.4865769398194597
5594
action (1

update weights
0.4865769398194597
5702
random action
action (4, 4, 2)
update weights
0.4865769398194597
5703
random action
action (1, 9, 0)
update weights
0.4865769398194597
5704
random action
action (0, 7, 3)
update weights
0.4865769398194597
5705
action (1, 0, 9)
update weights
0.4865769398194597
5706
random action
action (5, 4, 1)
update weights
0.4865769398194597
5707
random action
action (1, 8, 1)
update weights
0.4865769398194597
5708
action (1, 0, 9)
update weights
0.4865769398194597
5709
random action
action (2, 1, 7)
update weights
0.4865769398194597
5710
random action
action (2, 4, 4)
update weights
0.4865769398194597
5711
action (1, 0, 9)
update weights
0.4865769398194597
5712
action (1, 0, 9)
update weights
0.4865769398194597
5713
random action
action (3, 1, 6)
update weights
0.4865769398194597
5714
action (1, 0, 9)
update weights
0.4865769398194597
5715
random action
action (0, 9, 1)
update weights
0.4865769398194597
5716
action (1, 0, 9)
update weights
0.4865769398194597


update weights
0.4865769398194597
5821
random action
action (7, 3, 0)
update weights
0.4865769398194597
5822
random action
action (0, 8, 2)
update weights
0.4865769398194597
5823
action (1, 0, 9)
update weights
0.4865769398194597
5824
random action
action (1, 1, 8)
update weights
0.4865769398194597
5825
random action
s1의 전송이 deadline을 지나 완료됨
action (1, 3, 6)
update weights
source 0 전송완료
source 1 deadine 충족하지 못함
source 2 전송완료
모두 전송 완료
episode end
-----------------
-------------
Episode start 217

action [10, 0, 0]
0.4865769398194597
5826
action (1, 0, 9)
update weights
0.4865769398194597
5827
action (1, 0, 9)
update weights
0.4865769398194597
5828
action (1, 0, 9)
update weights
0.4865769398194597
5829
action (1, 0, 9)
update weights
0.4865769398194597
5830
s2의 전송이 deadline 안에 완료됨
action (1, 0, 9)
update weights
0.4865769398194597
5831
action (1, 0, 9)
update weights
0.4865769398194597
5832
action (1, 0, 9)
update weights
0.4865769398194597
5833
action (1, 0, 9)
update weights
0.4865769

update weights
0.4865769398194597
5945
action (1, 0, 9)
update weights
0.4865769398194597
5946
random action
action (6, 4, 0)
update weights
0.4865769398194597
5947
action (1, 0, 9)
update weights
0.4865769398194597
5948
random action
action (1, 5, 4)
update weights
0.4865769398194597
5949
s0의 전송이 deadline을 지나 완료됨
action (1, 0, 9)
update weights
0.4865769398194597
5950
action (1, 0, 9)
update weights
0.4865769398194597
5951
action (1, 0, 9)
update weights
0.4865769398194597
5952
random action
action (1, 5, 4)
update weights
0.4865769398194597
5953
action (1, 0, 9)
update weights
0.4865769398194597
5954
action (1, 0, 9)
update weights
0.4865769398194597
5955
action (1, 0, 9)
update weights
0.4865769398194597
5956
random action
action (7, 1, 2)
update weights
0.4865769398194597
5957
action (1, 0, 9)
update weights
0.4865769398194597
5958
random action
action (4, 4, 2)
update weights
0.4865769398194597
5959
random action
action (8, 0, 2)
update weights
0.4865769398194597
5960
random actio

update weights
0.01
6101
action (1, 0, 9)
update weights
0.01
6102
action (1, 0, 9)
update weights
0.01
6103
action (1, 0, 9)
update weights
0.01
6104
action (1, 0, 9)
update weights
0.01
6105
action (1, 0, 9)
update weights
0.01
6106
action (1, 0, 9)
update weights
0.01
6107
action (1, 0, 9)
update weights
0.01
6108
action (1, 0, 9)
update weights
0.01
6109
action (1, 0, 9)
update weights
0.01
6110
action (1, 0, 9)
update weights
0.01
6111
action (1, 0, 9)
update weights
0.01
6112
action (1, 0, 9)
update weights
0.01
6113
action (1, 0, 9)
update weights
0.01
6114
action (1, 0, 9)
update weights
0.01
6115
action (1, 0, 9)
update weights
0.01
6116
action (1, 0, 9)
update weights
0.01
6117
action (1, 0, 9)
update weights
0.01
6118
action (1, 0, 9)
update weights
0.01
6119
action (1, 0, 9)
update weights
0.01
6120
action (1, 0, 9)
update weights
0.01
6121
action (1, 0, 9)
update weights
0.01
6122
action (1, 0, 9)
update weights
0.01
6123
action (1, 0, 9)
update weights
0.01
6124
action (1

update weights
0.01
6296
action (1, 0, 9)
update weights
0.01
6297
action (1, 0, 9)
update weights
0.01
6298
action (1, 0, 9)
update weights
0.01
6299
action (1, 0, 9)
update weights
0.01
6300
action (1, 0, 9)
update weights
0.01
6301
action (1, 0, 9)
update weights
0.01
6302
action (1, 0, 9)
update weights
0.01
6303
action (1, 0, 9)
update weights
0.01
6304
action (1, 0, 9)
update weights
0.01
6305
action (1, 0, 9)
update weights
0.01
6306
action (1, 0, 9)
update weights
0.01
6307
action (1, 0, 9)
update weights
0.01
6308
action (1, 0, 9)
update weights
0.01
6309
action (1, 0, 9)
update weights
0.01
6310
action (1, 0, 9)
update weights
0.01
6311
action (1, 0, 9)
update weights
0.01
6312
action (1, 0, 9)
update weights
0.01
6313
action (1, 0, 9)
update weights
0.01
6314
action (1, 0, 9)
update weights
0.01
6315
action (1, 0, 9)
update weights
0.01
6316
action (1, 0, 9)
update weights
0.01
6317
action (1, 0, 9)
update weights
0.01
6318
action (1, 0, 9)
update weights
0.01
6319
action (1

update weights
0.01
6491
action (1, 0, 9)
update weights
0.01
6492
action (1, 0, 9)
update weights
0.01
6493
action (1, 0, 9)
update weights
0.01
6494
action (1, 0, 9)
update weights
0.01
6495
action (1, 0, 9)
update weights
0.01
6496
action (1, 0, 9)
update weights
0.01
6497
action (1, 0, 9)
update weights
0.01
6498
action (1, 0, 9)
update weights
0.01
6499
action (1, 0, 9)
update weights
0.01
6500
action (1, 0, 9)
update weights
0.01
6501
action (1, 0, 9)
update weights
0.01
6502
action (1, 0, 9)
update weights
0.01
6503
action (1, 0, 9)
update weights
0.01
6504
action (1, 0, 9)
update weights
0.01
6505
action (1, 0, 9)
update weights
0.01
6506
action (1, 0, 9)
update weights
0.01
6507
action (1, 0, 9)
update weights
0.01
6508
action (1, 0, 9)
update weights
0.01
6509
action (1, 0, 9)
update weights
0.01
6510
action (1, 0, 9)
update weights
0.01
6511
action (1, 0, 9)
update weights
0.01
6512
action (1, 0, 9)
update weights
0.01
6513
action (1, 0, 9)
update weights
0.01
6514
action (1

update weights
0.01
6687
action (1, 0, 9)
update weights
0.01
6688
action (1, 0, 9)
update weights
0.01
6689
action (1, 0, 9)
update weights
0.01
6690
action (1, 0, 9)
update weights
0.01
6691
action (1, 0, 9)
update weights
0.01
6692
action (1, 0, 9)
update weights
0.01
6693
action (1, 0, 9)
update weights
0.01
6694
action (1, 0, 9)
update weights
0.01
6695
action (1, 0, 9)
update weights
0.01
6696
action (1, 0, 9)
update weights
0.01
6697
action (1, 0, 9)
update weights
0.01
6698
action (1, 0, 9)
update weights
0.01
6699
action (1, 0, 9)
update weights
0.01
6700
action (1, 0, 9)
update weights
0.01
6701
action (1, 0, 9)
update weights
0.01
6702
action (1, 0, 9)
update weights
0.01
6703
action (1, 0, 9)
update weights
0.01
6704
action (1, 0, 9)
update weights
0.01
6705
action (1, 0, 9)
update weights
0.01
6706
action (1, 0, 9)
update weights
0.01
6707
action (1, 0, 9)
update weights
0.01
6708
action (1, 0, 9)
update weights
0.01
6709
action (1, 0, 9)
update weights
0.01
6710
action (1

update weights
0.01
6883
action (1, 0, 9)
update weights
0.01
6884
action (1, 0, 9)
update weights
0.01
6885
action (1, 0, 9)
update weights
0.01
6886
action (1, 0, 9)
update weights
0.01
6887
action (1, 0, 9)
update weights
0.01
6888
action (1, 0, 9)
update weights
0.01
6889
action (1, 0, 9)
update weights
0.01
6890
action (1, 0, 9)
update weights
0.01
6891
action (1, 0, 9)
update weights
0.01
6892
action (1, 0, 9)
update weights
0.01
6893
action (1, 0, 9)
update weights
0.01
6894
action (1, 0, 9)
update weights
0.01
6895
action (1, 0, 9)
update weights
0.01
6896
action (1, 0, 9)
update weights
0.01
6897
action (1, 0, 9)
update weights
0.01
6898
action (1, 0, 9)
update weights
0.01
6899
action (1, 0, 9)
update weights
0.01
6900
action (1, 0, 9)
update weights
0.01
6901
action (1, 0, 9)
update weights
0.01
6902
action (1, 0, 9)
update weights
0.01
6903
action (1, 0, 9)
update weights
0.01
6904
action (1, 0, 9)
update weights
0.01
6905
action (1, 0, 9)
update weights
0.01
6906
action (1

update weights
0.01
7079
action (1, 0, 9)
update weights
0.01
7080
action (1, 0, 9)
update weights
0.01
7081
action (1, 0, 9)
update weights
0.01
7082
action (1, 0, 9)
update weights
0.01
7083
action (1, 0, 9)
update weights
0.01
7084
action (1, 0, 9)
update weights
0.01
7085
action (1, 0, 9)
update weights
0.01
7086
action (1, 0, 9)
update weights
0.01
7087
action (1, 0, 9)
update weights
0.01
7088
action (1, 0, 9)
update weights
0.01
7089
action (1, 0, 9)
update weights
0.01
7090
action (1, 0, 9)
update weights
0.01
7091
action (1, 0, 9)
update weights
0.01
7092
action (1, 0, 9)
update weights
0.01
7093
action (1, 0, 9)
update weights
0.01
7094
action (1, 0, 9)
update weights
0.01
7095
action (1, 0, 9)
update weights
0.01
7096
action (1, 0, 9)
update weights
0.01
7097
action (1, 0, 9)
update weights
0.01
7098
action (1, 0, 9)
update weights
0.01
7099
action (1, 0, 9)
update weights
0.01
7100
action (1, 0, 9)
update weights
0.01
7101
action (1, 0, 9)
update weights
0.01
7102
action (1

update weights
0.01
7275
action (1, 0, 9)
update weights
0.01
7276
action (1, 0, 9)
update weights
0.01
7277
action (1, 0, 9)
update weights
0.01
7278
action (1, 0, 9)
update weights
0.01
7279
action (1, 0, 9)
update weights
0.01
7280
random action
action (9, 0, 1)
update weights
0.01
7281
action (1, 0, 9)
update weights
0.01
7282
action (1, 0, 9)
update weights
0.01
7283
action (1, 0, 9)
update weights
0.01
7284
action (1, 0, 9)
update weights
0.01
7285
action (1, 0, 9)
update weights
0.01
7286
action (1, 0, 9)
update weights
0.01
7287
action (1, 0, 9)
update weights
0.01
7288
action (1, 0, 9)
update weights
0.01
7289
action (1, 0, 9)
update weights
0.01
7290
action (1, 0, 9)
update weights
0.01
7291
action (1, 0, 9)
update weights
0.01
7292
action (1, 0, 9)
update weights
0.01
7293
action (1, 0, 9)
update weights
0.01
7294
action (1, 0, 9)
update weights
0.01
7295
action (1, 0, 9)
update weights
0.01
7296
action (1, 0, 9)
update weights
0.01
7297
action (1, 0, 9)
update weights
0.01


update weights
0.01
7471
action (1, 0, 9)
update weights
0.01
7472
action (1, 0, 9)
update weights
0.01
7473
action (1, 0, 9)
update weights
0.01
7474
action (1, 0, 9)
update weights
0.01
7475
action (1, 0, 9)
update weights
0.01
7476
action (1, 0, 9)
update weights
0.01
7477
action (1, 0, 9)
update weights
0.01
7478
action (1, 0, 9)
update weights
0.01
7479
action (1, 0, 9)
update weights
0.01
7480
action (1, 0, 9)
update weights
0.01
7481
action (1, 0, 9)
update weights
0.01
7482
action (1, 0, 9)
update weights
0.01
7483
action (1, 0, 9)
update weights
0.01
7484
action (1, 0, 9)
update weights
0.01
7485
action (1, 0, 9)
update weights
0.01
7486
action (1, 0, 9)
update weights
0.01
7487
action (1, 0, 9)
update weights
0.01
7488
action (1, 0, 9)
update weights
0.01
7489
action (1, 0, 9)
update weights
0.01
7490
action (1, 0, 9)
update weights
0.01
7491
action (1, 0, 9)
update weights
0.01
7492
action (1, 0, 9)
update weights
0.01
7493
action (1, 0, 9)
update weights
0.01
7494
action (1

update weights
0.01
7667
action (1, 0, 9)
update weights
0.01
7668
action (1, 0, 9)
update weights
0.01
7669
action (1, 0, 9)
update weights
0.01
7670
action (1, 0, 9)
update weights
0.01
7671
action (1, 0, 9)
update weights
0.01
7672
action (1, 0, 9)
update weights
0.01
7673
action (1, 0, 9)
update weights
0.01
7674
action (1, 0, 9)
update weights
0.01
7675
action (1, 0, 9)
update weights
0.01
7676
action (1, 0, 9)
update weights
0.01
7677
action (1, 0, 9)
update weights
0.01
7678
action (1, 0, 9)
update weights
0.01
7679
action (1, 0, 9)
update weights
0.01
7680
action (1, 0, 9)
update weights
0.01
7681
action (1, 0, 9)
update weights
0.01
7682
action (1, 0, 9)
update weights
0.01
7683
action (1, 0, 9)
update weights
0.01
7684
action (1, 0, 9)
update weights
0.01
7685
action (1, 0, 9)
update weights
0.01
7686
action (1, 0, 9)
update weights
0.01
7687
action (1, 0, 9)
update weights
0.01
7688
action (1, 0, 9)
update weights
0.01
7689
action (1, 0, 9)
update weights
0.01
7690
action (1

update weights
0.01
7863
action (1, 0, 9)
update weights
0.01
7864
action (1, 0, 9)
update weights
0.01
7865
action (1, 0, 9)
update weights
0.01
7866
action (1, 0, 9)
update weights
0.01
7867
action (1, 0, 9)
update weights
0.01
7868
action (1, 0, 9)
update weights
0.01
7869
action (1, 0, 9)
update weights
0.01
7870
action (1, 0, 9)
update weights
0.01
7871
action (1, 0, 9)
update weights
0.01
7872
action (1, 0, 9)
update weights
0.01
7873
action (1, 0, 9)
update weights
0.01
7874
action (1, 0, 9)
update weights
0.01
7875
action (1, 0, 9)
update weights
0.01
7876
action (1, 0, 9)
update weights
0.01
7877
action (1, 0, 9)
update weights
0.01
7878
action (1, 0, 9)
update weights
0.01
7879
action (1, 0, 9)
update weights
0.01
7880
action (1, 0, 9)
update weights
0.01
7881
action (1, 0, 9)
update weights
0.01
7882
action (1, 0, 9)
update weights
0.01
7883
action (1, 0, 9)
update weights
0.01
7884
action (1, 0, 9)
update weights
0.01
7885
action (1, 0, 9)
update weights
0.01
7886
action (1

update weights
0.01
8060
action (1, 0, 9)
update weights
0.01
8061
action (1, 0, 9)
update weights
0.01
8062
action (1, 0, 9)
update weights
0.01
8063
action (1, 0, 9)
update weights
0.01
8064
action (1, 0, 9)
update weights
0.01
8065
action (1, 0, 9)
update weights
0.01
8066
action (1, 0, 9)
update weights
0.01
8067
action (1, 0, 9)
update weights
0.01
8068
action (1, 0, 9)
update weights
0.01
8069
action (1, 0, 9)
update weights
0.01
8070
action (1, 0, 9)
update weights
0.01
8071
action (1, 0, 9)
update weights
0.01
8072
action (1, 0, 9)
update weights
0.01
8073
action (1, 0, 9)
update weights
0.01
8074
action (1, 0, 9)
update weights
0.01
8075
action (1, 0, 9)
update weights
0.01
8076
action (1, 0, 9)
update weights
0.01
8077
action (1, 0, 9)
update weights
0.01
8078
action (1, 0, 9)
update weights
0.01
8079
action (1, 0, 9)
update weights
0.01
8080
action (1, 0, 9)
update weights
0.01
8081
action (1, 0, 9)
update weights
0.01
8082
action (1, 0, 9)
update weights
0.01
8083
action (1

update weights
0.01
8256
action (1, 0, 9)
update weights
0.01
8257
action (1, 0, 9)
update weights
0.01
8258
action (1, 0, 9)
update weights
0.01
8259
action (1, 0, 9)
update weights
0.01
8260
action (1, 0, 9)
update weights
0.01
8261
action (1, 0, 9)
update weights
0.01
8262
action (1, 0, 9)
update weights
0.01
8263
action (1, 0, 9)
update weights
0.01
8264
action (1, 0, 9)
update weights
0.01
8265
action (1, 0, 9)
update weights
0.01
8266
action (1, 0, 9)
update weights
0.01
8267
action (1, 0, 9)
update weights
0.01
8268
action (1, 0, 9)
update weights
0.01
8269
action (1, 0, 9)
update weights
0.01
8270
action (1, 0, 9)
update weights
0.01
8271
action (1, 0, 9)
update weights
0.01
8272
action (1, 0, 9)
update weights
0.01
8273
action (1, 0, 9)
update weights
0.01
8274
action (1, 0, 9)
update weights
0.01
8275
action (1, 0, 9)
update weights
0.01
8276
action (1, 0, 9)
update weights
0.01
8277
action (1, 0, 9)
update weights
0.01
8278
action (1, 0, 9)
update weights
0.01
8279
action (1

update weights
0.01
8452
action (1, 0, 9)
update weights
0.01
8453
action (1, 0, 9)
update weights
0.01
8454
action (1, 0, 9)
update weights
0.01
8455
action (1, 0, 9)
update weights
0.01
8456
action (1, 0, 9)
update weights
0.01
8457
action (1, 0, 9)
update weights
0.01
8458
action (1, 0, 9)
update weights
0.01
8459
action (1, 0, 9)
update weights
0.01
8460
action (1, 0, 9)
update weights
0.01
8461
action (1, 0, 9)
update weights
0.01
8462
action (1, 0, 9)
update weights
0.01
8463
action (1, 0, 9)
update weights
0.01
8464
action (1, 0, 9)
update weights
0.01
8465
action (1, 0, 9)
update weights
0.01
8466
action (1, 0, 9)
update weights
0.01
8467
action (1, 0, 9)
update weights
0.01
8468
action (1, 0, 9)
update weights
0.01
8469
action (1, 0, 9)
update weights
0.01
8470
action (1, 0, 9)
update weights
0.01
8471
action (1, 0, 9)
update weights
0.01
8472
action (1, 0, 9)
update weights
0.01
8473
action (1, 0, 9)
update weights
0.01
8474
action (1, 0, 9)
update weights
0.01
8475
action (1

update weights
0.01
8647
action (1, 0, 9)
update weights
0.01
8648
action (1, 0, 9)
update weights
0.01
8649
action (1, 0, 9)
update weights
0.01
8650
action (1, 0, 9)
update weights
0.01
8651
action (1, 0, 9)
update weights
0.01
8652
action (1, 0, 9)
update weights
0.01
8653
action (1, 0, 9)
update weights
0.01
8654
action (1, 0, 9)
update weights
0.01
8655
action (1, 0, 9)
update weights
0.01
8656
action (1, 0, 9)
update weights
0.01
8657
action (1, 0, 9)
update weights
0.01
8658
action (1, 0, 9)
update weights
0.01
8659
action (1, 0, 9)
update weights
0.01
8660
action (1, 0, 9)
update weights
0.01
8661
action (1, 0, 9)
update weights
0.01
8662
action (1, 0, 9)
update weights
0.01
8663
action (1, 0, 9)
update weights
0.01
8664
action (1, 0, 9)
update weights
0.01
8665
action (1, 0, 9)
update weights
0.01
8666
action (1, 0, 9)
update weights
0.01
8667
action (1, 0, 9)
update weights
0.01
8668
action (1, 0, 9)
update weights
0.01
8669
action (1, 0, 9)
update weights
0.01
8670
action (1

update weights
0.01
8842
action (1, 0, 9)
update weights
0.01
8843
action (1, 0, 9)
update weights
0.01
8844
action (1, 0, 9)
update weights
0.01
8845
action (1, 0, 9)
update weights
0.01
8846
action (1, 0, 9)
update weights
0.01
8847
action (1, 0, 9)
update weights
0.01
8848
action (1, 0, 9)
update weights
0.01
8849
action (1, 0, 9)
update weights
0.01
8850
action (1, 0, 9)
update weights
0.01
8851
action (1, 0, 9)
update weights
0.01
8852
action (1, 0, 9)
update weights
0.01
8853
action (1, 0, 9)
update weights
0.01
8854
action (1, 0, 9)
update weights
0.01
8855
action (1, 0, 9)
update weights
0.01
8856
action (1, 0, 9)
update weights
0.01
8857
action (1, 0, 9)
update weights
0.01
8858
action (1, 0, 9)
update weights
0.01
8859
action (1, 0, 9)
update weights
0.01
8860
action (1, 0, 9)
update weights
0.01
8861
action (1, 0, 9)
update weights
0.01
8862
action (1, 0, 9)
update weights
0.01
8863
action (1, 0, 9)
update weights
0.01
8864
action (1, 0, 9)
update weights
0.01
8865
action (1

update weights
0.01
9037
action (1, 0, 9)
update weights
0.01
9038
action (1, 0, 9)
update weights
0.01
9039
action (1, 0, 9)
update weights
0.01
9040
action (1, 0, 9)
update weights
0.01
9041
action (1, 0, 9)
update weights
0.01
9042
action (1, 0, 9)
update weights
0.01
9043
action (1, 0, 9)
update weights
0.01
9044
action (1, 0, 9)
update weights
0.01
9045
action (1, 0, 9)
update weights
0.01
9046
action (1, 0, 9)
update weights
0.01
9047
action (1, 0, 9)
update weights
0.01
9048
action (1, 0, 9)
update weights
0.01
9049
action (1, 0, 9)
update weights
0.01
9050
action (1, 0, 9)
update weights
0.01
9051
action (1, 0, 9)
update weights
0.01
9052
action (1, 0, 9)
update weights
0.01
9053
action (1, 0, 9)
update weights
0.01
9054
action (1, 0, 9)
update weights
0.01
9055
action (1, 0, 9)
update weights
0.01
9056
action (1, 0, 9)
update weights
0.01
9057
action (1, 0, 9)
update weights
0.01
9058
action (1, 0, 9)
update weights
0.01
9059
action (1, 0, 9)
update weights
0.01
9060
action (1

update weights
0.01
9233
action (1, 0, 9)
update weights
0.01
9234
action (1, 0, 9)
update weights
0.01
9235
action (1, 0, 9)
update weights
0.01
9236
action (1, 0, 9)
update weights
0.01
9237
action (1, 0, 9)
update weights
0.01
9238
action (1, 0, 9)
update weights
0.01
9239
action (1, 0, 9)
update weights
0.01
9240
action (1, 0, 9)
update weights
0.01
9241
action (1, 0, 9)
update weights
0.01
9242
action (1, 0, 9)
update weights
0.01
9243
action (1, 0, 9)
update weights
0.01
9244
action (1, 0, 9)
update weights
0.01
9245
action (1, 0, 9)
update weights
0.01
9246
action (1, 0, 9)
update weights
0.01
9247
action (1, 0, 9)
update weights
0.01
9248
action (1, 0, 9)
update weights
0.01
9249
action (1, 0, 9)
update weights
0.01
9250
action (1, 0, 9)
update weights
0.01
9251
action (1, 0, 9)
update weights
0.01
9252
action (1, 0, 9)
update weights
0.01
9253
action (1, 0, 9)
update weights
0.01
9254
action (1, 0, 9)
update weights
0.01
9255
action (1, 0, 9)
update weights
0.01
9256
action (1

KeyboardInterrupt: 

이렇게 하나의 action에 수렴하는 이유가 혹시 target update 시 action_id에 할당하는 Q값때문이 아닌가..?

In [3]:
flow_success

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


In [22]:
rate=[]
flow_success=np.array(flow_success)
for i in range(int(len(flow_success)/3)):#200개당평균
    print(flow_success[3*i:3*(i+1)])
    rate.append(np.mean(flow_success[3*i:3*(i+1)]))
    print(np.mean(flow_success[3*i:3*(i+1)]))


[1 0 0]
0.3333333333333333
[1 0 0]
0.3333333333333333
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 0 1]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 0 1]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 0 1]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 0 0]
0.3333333333333333
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[

0.6666666666666666
[1 1 1]
1.0
[1 1 1]
1.0
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 1]
1.0
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 1]
1.0
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 0 1]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 0 1]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 1]
1

1.0
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 0 1]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 0 0]
0.3333333333333333
[1 1 1]
1.0
[1 1 1]
1.0
[1 0 0]
0.3333333333333333
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 1]
1.0
[1 0 1]
0.6666666666666666
[1 1 1]
1.0
[1 0 0]
0.3333333333333333
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 0 1]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 0 0]
0.3333333333333333
[1 0 0]
0.3333333333333333
[1 0 0]
0.3333333333333333
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 0 0]
0.3333333333333333
[1 0 0]
0.3333333333333333
[1 0 0]
0.3333333333333333
[1 1 0]
0.6666666666666666
[1 0 0]
0.3333333333333333
[1 1 1]
1.0
[1 0 0]
0.3333333333333333
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 1]
1.0
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 

0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 0 1]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 0 1]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 0 1]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 0 0]
0.3333333333333333
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 0 0]
0.3333333333333333
[1 1 0]
0.6666666666666666
[1 0 1]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 0 0]
0.3333333333333333
[1 1 1]
1.0
[1 1 1]
1.0
[1 0 0]
0.3333333333333333
[1 0 0]
0.3333333333333333
[1 1 0]
0.6666666666666666
[1 

0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 1]
1.0
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 0 1]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 0 0]
0.3333333333333333
[1 0 0]
0.3333333333333333
[1 0 1]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 0 0]
0.3333333333333333
[1 0 0]
0.3333333333333333
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 0 1]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0

[1 0 0]
0.3333333333333333
[1 0 0]
0.3333333333333333
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 1]
1.0
[1 0 0]
0.3333333333333333
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 0 1]
0.6666666666666666
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 1]
1.0
[1 0 0]
0.3333333333333333
[1 1 1]
1.0
[1 0 0]
0.3333333333333333
[1 0 0]
0.3333333333333333
[1 1 1]
1.0
[1 1 1]
1.0
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 0 1]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 0 0]
0.3333333333333333
[1 1 0]
0.6666666666666666
[1 0 0]
0.3333333333333333
[1 0 0]
0.3333333333333333
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[1 1 0]
0.6666666666666666
[

In [ ]:
from matplotlib import pyplot as plt
import numpy as np

# x = mse_loss

# plt.plot(x)
# plt.show()

#flow_success_rate=
x2 = rate

plt.plot(x2)
plt.show()

KeyboardInterrupt: 

In [74]:
len(mse_loss)

1968

1.할 것 : flow update interval을 줄이기 (0.001초?) 어느정도가 적당할 지 교수님꼐여줘보기

2.reward의 문제점: drem(deadline까지 남아있는 시간)이 가장 짧은 source에 많은 pacing rate를 할당할 수록 높은 reward가 주어지는데, file size를 고려하지 않았다는 문제점이 있다. deadline이 아니라 min rate를 기준으로 해야할듯, 그리고 9:1과 같은 극단적비율로 학습됨 

3.state=0인 경우 filesize=0이란뜻이므로 action을 0으로 할당하는 코드를 짜야함. 문제는 두개의 filesize가 0인경우 어떻게 하냐는것...!!!!! -> state가 0인 index에 따라 action도 0인 allowed_action의 index를 찾고, 그 중 가장 큰 maxQ값을 갖는 action 선택 
bug: source2(3번째 소스)의 state가 0 이면 action을 3,3,4로 할당(원인은 모름)

4.10만초 동안 가동

5.deadline이 지나면 음수까지 내려가는 버전으로 돌려보기 > 이것은 안됨... value가 deadline이 0이면 0이되도록 설정했기때문에 deadline이 음수가 되면 value가 1이 됨



In [28]:
A=list(range(11))
B=list(range(11))
C=list(range(11)) #합이 10이 되는 0~10까지의 수 조합
allowed_actions=[]
for i in list(product(*(A,B,C))):
    if sum(list(i))==10:
        allowed_actions.append(i) #d는 66개의 조합
        
allowed_actions.index((0,10,0))
#print (allowed_actions)

10

In [12]:
state=np.array([3,3,3])
np.array(state).reshape(1,state.shape[0])

array([[3, 3, 3]])

In [82]:
#deeplearning없이 시뮬레이션
env = simpy.Environment()

request = {
    'sources' : sources,
    'destinations' : destinations, 
    'filesize' : [random.randrange(50,100) for source in sources], #단위는 Gbps
    'deadline' : [random.randrange(5,30) for source in sources], 
    'value' : [None for source in sources], #아직 전송되지 않았으면 None, 제시간에 전송되었으면 1, 제시간에 전송되지 않았으면 0
}

print ("source 0의 filesize:",request['filesize'][0])
print ("source 1의 filesize:",request['filesize'][1])
print ("source 2의 filesize:",request['filesize'][2])

action=[3,3,4]

Tfu=1

def flowUpdate_interval(env,action,Tfu): #Tsc에서의 action(pacint rate)가 n번의 flow update interval만큼 유지된다.
    #print("flow update interval :",env.now)
    global request
    fs=request['filesize']
    #src=request['sources']
    while True:
        print("flow update interval :",env.now)
        if ((fs[0]!=0)or(fs[1]!=0)or(fs[2]!=0)): #하나라도 0이상으로 남아있으면
            
            print("전송중!영차영차")
            
            for s in range(len(sources)):#0밑으로는 안떨어지게, 전역변수 request의 값을 변경
                request['filesize'][s]=max([request['filesize'][s]-action[s],0]) 
                request['deadline'][s]=max([request['deadline'][s]-1,0])
                if ((request['filesize'][s]==0) and (request['value'][s]==None)): #아직 완료되지 않았던 flow가 전송이 완료되면?
                    #print ("s{}의 전송이 완료됨".format(s))
                    if (request['deadline'][s]!=0): #기간 안에 전송되면?
                        request['value'][s]=1 #value를 1로 변경
                        print ("s{}의 전송이 deadline 안에 완료됨".format(s))
                    else: #기간안에 전송된게 아니라면(value초기값은 None)
                        request['value'][s]=0
                        print ("s{}의 전송이 deadline을 지나 완료됨".format(s))
            
            yield env.timeout(Tfu) 
        elif ((fs[0]==0)and(fs[1]==0)and(fs[2]==0)):
            print ("종료:",env.now)
            return #모든 flow의 전송이 완료되면 종료
        
        
proc=env.process(flowUpdate_interval(env,action,Tfu))
env.run(until=proc)

source 0의 filesize: 87
source 1의 filesize: 56
source 2의 filesize: 78
flow update interval : 0
전송중!영차영차
flow update interval : 1
전송중!영차영차
flow update interval : 2
전송중!영차영차
flow update interval : 3
전송중!영차영차
flow update interval : 4
전송중!영차영차
flow update interval : 5
전송중!영차영차
flow update interval : 6
전송중!영차영차
flow update interval : 7
전송중!영차영차
flow update interval : 8
전송중!영차영차
flow update interval : 9
전송중!영차영차
flow update interval : 10
전송중!영차영차
flow update interval : 11
전송중!영차영차
flow update interval : 12
전송중!영차영차
flow update interval : 13
전송중!영차영차
flow update interval : 14
전송중!영차영차
flow update interval : 15
전송중!영차영차
flow update interval : 16
전송중!영차영차
flow update interval : 17
전송중!영차영차
flow update interval : 18
전송중!영차영차
s1의 전송이 deadline 안에 완료됨
flow update interval : 19
전송중!영차영차
s2의 전송이 deadline 안에 완료됨
flow update interval : 20
전송중!영차영차
flow update interval : 21
전송중!영차영차
flow update interval : 22
전송중!영차영차
flow update interval : 23
전송중!영차영차
flow update interval : 24
전송중!영차영차
flow update interv